force-app/main/default/objects/AccountMirror__c/AccountMirror__c.object-meta.xml
<CustomObject>
    <label>Account Mirror</label>
    <nameField>
        <label>Account Mirror Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AccountMirror</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountMirror__c/fields/MirrorId__c.field-meta.xml
<CustomField>
    <fullName>MirrorId__c</fullName>
    <externalId>true</externalId>
    <label>MirrorId</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SM001_AccountManager.cls
public with sharing class SM001_AccountManager {
    public static void manageMirroring(List<Account> newAccounts) {
        List<AccountMirror__c> mirroredAccounts = new List<AccountMirror__c>();

        for(Account acc : newAccounts) {
            AccountMirror__c mirror = (AccountMirror__c) U001_SObjectUtils.getMirroredSObject(acc);
            mirror.MirrorId__c = acc.Id;
            mirroredAccounts.add(mirror);
        }

        System.debug('###### mirroredAccounts : ' + mirroredAccounts);

        TM000_TriggerHandler.ByPassAllTriggers = true;
        upsert mirroredAccounts MirrorId__c;
        TM000_TriggerHandler.ByPassAllTriggers = false;
    }
}