force-app/main/default/objects/AccountMirror__c/AccountMirror__c.object-meta.xml
<CustomObject>
    <label>Account Mirror</label>
    <nameField>
        <label>Account Mirror Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AccountMirror</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountMirror__c/fields/MirrorId__c.field-meta.xml
<CustomField>
    <fullName>MirrorId__c</fullName>
    <externalId>true</externalId>
    <label>MirrorId</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SM002_AccountMirrorManager.cls
public with sharing class SM002_AccountMirrorManager {
    public static void manageMirroring(List<AccountMirror__c> newAccounts) {
        List<Account> mirroredAccounts = new List<Account>();

        for(AccountMirror__c acc : newAccounts) {
            Account mirror = (Account) U001_SObjectUtils.getMirroredSObject(acc);
            mirror.Id = acc.MirrorId__c;
            mirroredAccounts.add(mirror);
        }

        System.debug('###### mirroredAccounts : ' + mirroredAccounts);

        TM000_TriggerHandler.ByPassAllTriggers = true;
        upsert mirroredAccounts;
        TM000_TriggerHandler.ByPassAllTriggers = false;
    }
}